Revert "Update to latest upstream tree-sitter release v0.26.0"
This reverts commit dfd28af18250b0f2801ecb4eda538da1bba845e6. Seems emacs currently
fails to compile against it:

    treesit.c: In function ‘treesit_load_language’:
    treesit.c:749:42: error: implicit declaration of function ‘ts_language_version’; did you mean ‘ts_language_abi_version’? [-Wimplicit-function-declaration]
      749 |                             make_fixnum (ts_language_version (lang)));
          |                                          ^~~~~~~~~~~~~~~~~~~
          |                                          ts_language_abi_version